name: Validate Module

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  validate-powershell:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Show PowerShell Version
        shell: powershell
        run: |
          $PSVersionTable

      - name: Validate Manifest
        shell: powershell
        run: |
          Test-ModuleManifest .\src\SnmpTools.psd1

      - name: Verify Module Import and Exported Functions
        shell: powershell
        run: |
          Import-Module .\src\SnmpTools.psd1 -Force
          
          $manifest = Test-ModuleManifest .\src\SnmpTools.psd1

          $expected = $manifest.ExportedFunctions.Keys | Sort-Object
          $actual = (Get-Command -Module SnmpTools).Name | Sort-Object

          $difference = Compare-Object $expected $actual

          if ($difference) {
              throw "Exported commands do not match manifest."
          }

  validate-powershell-7:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Show PowerShell Version
        shell: pwsh
        run: |
          $PSVersionTable

      - name: Validate Manifest
        shell: pwsh
        run: |
          Test-ModuleManifest .\src\SnmpTools.psd1
      
      - name: Verify Module Import and Exported Functions
        shell: pwsh
        run: |
          Import-Module .\src\SnmpTools.psd1 -Force
          
          $manifest = Test-ModuleManifest .\src\SnmpTools.psd1

          $expected = $manifest.ExportedFunctions.Keys | Sort-Object
          $actual = (Get-Command -Module SnmpTools).Name | Sort-Object
          
          $difference = Compare-Object $expected $actual

          if ($difference) {
              throw "Exported commands do not match manifest."
          }